{{- if .Values.ldap.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dcm4chee.fullname" . }}-ldap-data
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.ldap.storage.storageClass }}
  storageClassName: {{ .Values.ldap.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ldap.storage.size }}
{{- end }}
---
{{- if .Values.arc.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dcm4chee.fullname" . }}-arc-data
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
    app.kubernetes.io/component: arc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.arc.storage.storageClass }}
  storageClassName: {{ .Values.arc.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.arc.storage.size }}
{{- end }}
