{{- if .Values.arc.dicomNodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcm4chee.fullname" . }}-arc-dicom
  labels:
    {{- include "dcm4chee.labels" . | nindent 4 }}
    app.kubernetes.io/component: arc
spec:
  type: NodePort
  ports:
    - port: {{ .Values.arc.service.dicomPort }}
      targetPort: 11112
      protocol: TCP
      name: dicom
      {{- if .Values.arc.dicomNodePort.nodePort }}
      nodePort: {{ .Values.arc.dicomNodePort.nodePort }}
      {{- end }}
  selector:
    {{- include "dcm4chee.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: arc
{{- end }}
